/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GiaodienUI;

import BUS.DiaDiem;
import BUS.DiaDiemVuiChoi;
import BUS.NhanVien;
import DTO.DiaDiemDTO;
import KetnoiSQL_DAL.config;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thanh Tran
 */
public class QlyDiaDiemTour extends javax.swing.JPanel {
    DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form QlyKhachSan
     */
    DiaDiem dd = new DiaDiem();
    config con = new config();
    
    /**
     * Creates new form QlyDiaDiemTour
     */
    public QlyDiaDiemTour() {
        initComponents();        
        model = (DefaultTableModel) jTable1.getModel();
        for(int i = 0 ; i < dd.laySoLuongDiaDiem() ; i++ ) {
                model.addRow(new Object[]{dd.traDiaDiem(i).getKhuvuc(),dd.traDiaDiem(i).getThuoctinh(),dd.traDiaDiem(i).getTendd(),dd.traDiaDiem(i).getMadd()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        cbxKhuVuc = new javax.swing.JComboBox<>();
        cbxDiaDiem = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        cbxTinhThanhPho = new javax.swing.JComboBox<>();
        btnReset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(167, 169, 177));

        jPanel4.setBackground(new java.awt.Color(167, 169, 177));

        jLabel5.setBackground(new java.awt.Color(255, 204, 204));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(169, 0, 6));
        jLabel5.setText("                        Hệ Thống Quản Lý Địa Điểm Tour");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE)
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.setBackground(new java.awt.Color(167, 169, 177));

        cbxKhuVuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn Khu Vực", "Miền Nam", "Miền Trung", "Miền Bắc" }));
        cbxKhuVuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxKhuVucActionPerformed(evt);
            }
        });

        cbxDiaDiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn Địa Điểm" }));
        cbxDiaDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDiaDiemActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        btnThem.setBackground(new java.awt.Color(21, 110, 71));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(21, 110, 71));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(21, 110, 71));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnTimKiem.setBackground(new java.awt.Color(21, 110, 71));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        cbxTinhThanhPho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn Tỉnh / Thành Phố", "Thành phố Hồ Chí Minh", "Bà Rịa - Vũng Tàu", "Đà Nẵng", "Huế", "Hà Nội" }));
        cbxTinhThanhPho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTinhThanhPhoActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(21, 110, 71));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(cbxKhuVuc, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(cbxTinhThanhPho, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                        .addComponent(cbxDiaDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTimKiem)
                                .addGap(64, 64, 64)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(94, 94, 94))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxDiaDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxKhuVuc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTinhThanhPho, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThem)
                        .addComponent(btnXoa))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnReset)
                        .addComponent(btnTimKiem)
                        .addComponent(btnSua)))
                .addGap(32, 32, 32))
        );

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Khu Vực", "Tỉnh/Thành phố", "Địa Điểm", "Mã Địa Điểm"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbxKhuVucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxKhuVucActionPerformed
        String khuVuc = cbxKhuVuc.getSelectedItem().toString();
        if(khuVuc.equals("Miền Nam")){
            cbxTinhThanhPho.removeAllItems();
            cbxTinhThanhPho.addItem("Thành phố Hồ Chí Minh");
            cbxTinhThanhPho.addItem("Bà Rịa - Vũng Tàu");

        }
        else if(khuVuc.equals("Miền Trung")){
            cbxTinhThanhPho.removeAllItems();
                        cbxTinhThanhPho.addItem("Đà Nẵng");
            cbxTinhThanhPho.addItem("Huế");

        }
        else if(khuVuc.equals("Miền Bắc")){
            cbxTinhThanhPho.removeAllItems();
                        cbxTinhThanhPho.addItem("Hà Nội");
            cbxTinhThanhPho.addItem("Hải Phòng");

        }
    }//GEN-LAST:event_cbxKhuVucActionPerformed

    private void cbxDiaDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDiaDiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDiaDiemActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        String kVuc = cbxKhuVuc.getSelectedItem().toString();
        String tinhTP = cbxTinhThanhPho.getSelectedItem().toString();
                String diaDiem = cbxDiaDiem.getSelectedItem().toString();
                
                if(kVuc.equals("Chọn Khu Vực")){
                                        JOptionPane.showMessageDialog(null,"Vui Lòng Kiểm Tra Lại Và Thêm Đầy Đủ Thông Tin");

                }
                else if(tinhTP.equals("Chọn Tỉnh / Thành Phố")){
                                        JOptionPane.showMessageDialog(null,"Vui Lòng Kiểm Tra Lại Và Thêm Đầy Đủ Thông Tin");

                }
                else if(diaDiem.equals("Chọn Địa Điểm")){
                                        JOptionPane.showMessageDialog(null,"Vui Lòng Kiểm Tra Lại Và Thêm Đầy Đủ Thông Tin");

                }
                else{
                    int maxMaDD = dd.laySoLuongDiaDiem();
                    String maDiaDiem = "DD" + String.format("%04d", maxMaDD + 1);
                    
                    dd.themDiaDiem(maDiaDiem, diaDiem, tinhTP, kVuc);
                    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
               
                model.addRow(new Object[]{dd.traDiaDiem(maDiaDiem).getKhuvuc(),dd.traDiaDiem(maDiaDiem).getThuoctinh(),dd.traDiaDiem(maDiaDiem).getTendd(),dd.traDiaDiem(maDiaDiem).getMadd()});
                
                jTable1.setModel(model);
                
                JOptionPane.showMessageDialog(null,"Thêm Địa Điểm Thành Công");
                }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int selectedRow = jTable1.getSelectedRow();
// nếu không có hàng nào được chọn, thông báo lỗi và kết thúc
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Vui Lòng Chọn Một Hàng Để Xóa");
            return;
        }

// lấy ra model của JTable hiện tại
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

// lấy mã khách hàng của hàng được chọn
        String maDiaDiem = (String) model.getValueAt(selectedRow, 3);

        boolean a = dd.xoaDiaDiem(maDiaDiem);
        
        model.removeRow(selectedRow);

// cập nhật lại model cho JTable
        jTable1.setModel(model);

// thông báo thành công
        JOptionPane.showMessageDialog(null, "Xóa địa điểm Thành Công");

    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        
        if(selectedRow == -1 ){
            JOptionPane.showMessageDialog(null, "vui Lòng Chọn 1 Địa Điểm Để Sửa");
        }
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String maDD = (String) model.getValueAt(selectedRow,3);
        
        dd.traDiaDiem(maDD);
        JComboBox<String> cbxKhuVuc = new JComboBox<>();
        cbxKhuVuc.addItem("Miền Nam");
        cbxKhuVuc.addItem("Miền Trung");
        cbxKhuVuc.addItem("Miền Bắc");
        cbxKhuVuc.setSelectedItem(dd.traDiaDiem(maDD).getKhuvuc());
        JOptionPane.showMessageDialog(null,cbxKhuVuc, "Chọn khu vực", JOptionPane.QUESTION_MESSAGE);
        String khuVuc = cbxKhuVuc.getSelectedItem().toString();
        
        JComboBox<String> cbxTinhThanhPho = new JComboBox<>();
        
        if(khuVuc.equals("Miền Nam")){
            cbxTinhThanhPho.addItem("Thành phố Hồ CHí Minh");
                        cbxTinhThanhPho.addItem("Bà Rịa - Vũng Tàu");

        }
        else if(khuVuc.equals("Miền Trung")){
                        cbxTinhThanhPho.addItem("Đà Nẵng");
            cbxTinhThanhPho.addItem("Huế");

        }
        else if(khuVuc.equals("Miền Bắc")){
                        cbxTinhThanhPho.addItem("Hà Nội");
            cbxTinhThanhPho.addItem("Hải Phòng");

        }
        cbxTinhThanhPho.setSelectedItem(dd.traDiaDiem(maDD).getThuoctinh());
        JOptionPane.showMessageDialog(null,cbxTinhThanhPho, "Chọn tỉnh/thành phố", JOptionPane.QUESTION_MESSAGE);
        String tinhTP = cbxTinhThanhPho.getSelectedItem().toString();
        
        JComboBox<String> cbxDiaDiem = new JComboBox<>();
        if(tinhTP.equals("Thành phố Hồ Chí Minh")){
            cbxDiaDiem.addItem("Dinh Độc Lập - Hội trường Thống Nhất");
            cbxDiaDiem.addItem("Bảo tàng thành phố Hồ Chí Minh");

        }
        else if(tinhTP.equals("Bà Rịa - Vũng Tàu")){
            cbxDiaDiem.addItem("Ngọn Hải Đăng Vũng Tàu");
            cbxDiaDiem.addItem("Bạch Dinh");
        }
        else if(tinhTP.equals("Đà Nẵng")){
            cbxDiaDiem.addItem("Ba Na Hills");
            cbxDiaDiem.addItem("Ngũ Hành Sơn");

        }
        else if(tinhTP.equals("Huế")){
            cbxDiaDiem.addItem("Đồi Vọng Cảnh");
            cbxDiaDiem.addItem("Lăng Khải Định");
        }
        else if(tinhTP.equals("Hà Nội")){
            cbxDiaDiem.addItem("Quảng Trường Ba Đình - Lăng Bác");
            cbxDiaDiem.addItem("Văn Miếu Quốc Tử Giám");

        }
        else if(tinhTP.equals("Hải Phòng")){
            cbxDiaDiem.addItem("Vịnh Lan Hạ");
            cbxDiaDiem.addItem("Bảo Tàng Hải Phòng");
        }
        cbxDiaDiem.setSelectedItem(dd.traDiaDiem(maDD).getTendd());
        JOptionPane.showMessageDialog(null,cbxDiaDiem, "Chọn địa điểm", JOptionPane.QUESTION_MESSAGE);
        String diaDiem = cbxDiaDiem.getSelectedItem().toString();
        
        String maDiaDiemNew = JOptionPane.showInputDialog(null,"Nhập Mã Địa Điểm",dd.traDiaDiem(maDD).getMadd());
        
        dd.suaDiaDiem(maDD, maDiaDiemNew, diaDiem, tinhTP, khuVuc);

        model.setValueAt(khuVuc,selectedRow,0);
        model.setValueAt(tinhTP,selectedRow,1);
        model.setValueAt(diaDiem,selectedRow,2);
        model.setValueAt(maDiaDiemNew,selectedRow,3);
                
        JOptionPane.showMessageDialog(null,"Sửa Địa Điểm Thành Công");
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String dkTim = JOptionPane.showInputDialog(null, "Nhập điều kiện tìm !"," ");

// Tạo một danh sách để lưu khách hàng tìm được
       dd.timDiaDiemUnlimit(dkTim);

// Kiểm tra kết quả tìm kiếm
        if (dd.timDiaDiemUnlimit(dkTim) == null) {
            JOptionPane.showMessageDialog(null, "Kết Quả Không Tìm Thấy");
        } else {
            // Tạo một model mới để hiển thị kết quả tìm kiếm trên JTable
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Khu Vực");
            model.addColumn("Tỉnh/Thành Phố");
            model.addColumn("Địa Điểm");
            model.addColumn("Mã Địa Điểm");

            // Thêm các khách hàng tìm được vào model
            for (DiaDiemDTO kh : dd.timDiaDiemUnlimit(dkTim)) {              
            
                model.addRow(new Object[]{kh.getKhuvuc(), kh.getThuoctinh(), kh.getTendd(), kh.getMadd()});
            }

            // Cập nhật lại model cho JTable
            jTable1.setModel(model);
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed
 
    private void cbxTinhThanhPhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTinhThanhPhoActionPerformed
        String tinhTP = cbxTinhThanhPho.getSelectedItem().toString();
        if(tinhTP.equals("Thành phố Hồ Chí Minh")){
            cbxDiaDiem.removeAllItems();
            cbxDiaDiem.addItem("Dinh Độc Lập - Hội trường Thống Nhất");
            cbxDiaDiem.addItem("Bảo tàng thành phố Hồ Chí Minh");

        }
        else if(tinhTP.equals("Bà Rịa - Vũng Tàu")){
                        cbxDiaDiem.removeAllItems();
            cbxDiaDiem.addItem("Ngọn Hải Đăng Vũng Tàu");
            cbxDiaDiem.addItem("Bạch Dinh");
        }
        else if(tinhTP.equals("Đà Nẵng")){
            cbxDiaDiem.removeAllItems();
            cbxDiaDiem.addItem("Ba Na Hills");
            cbxDiaDiem.addItem("Ngũ Hành Sơn");

        }
        else if(tinhTP.equals("Huế")){
            cbxDiaDiem.removeAllItems();
            cbxDiaDiem.addItem("Đồi Vọng Cảnh");
            cbxDiaDiem.addItem("Lăng Khải Định");
        }
        else if(tinhTP.equals("Hà Nội")){
            cbxDiaDiem.removeAllItems();
            cbxDiaDiem.addItem("Quảng Trường Ba Đình - Lăng Bác");
            cbxDiaDiem.addItem("Văn Miếu Quốc Tử Giám");

        }
        else if(tinhTP.equals("Hải Phòng")){
            cbxDiaDiem.removeAllItems();
            cbxDiaDiem.addItem("Vịnh Lan Hạ");
            cbxDiaDiem.addItem("Bảo Tàng Hải Phòng");
        }
    }//GEN-LAST:event_cbxTinhThanhPhoActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        model = (DefaultTableModel) jTable1.getModel();
        for (int i = 0; i < dd.laySoLuongDiaDiem(); i++) {
            model.addRow(new Object[]{dd.traDiaDiem(i).getKhuvuc(), dd.traDiaDiem(i).getThuoctinh(), dd.traDiaDiem(i).getTendd(), dd.traDiaDiem(i).getMadd()});
        }
        jTable1.setModel(model);

    }//GEN-LAST:event_btnResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbxDiaDiem;
    private javax.swing.JComboBox<String> cbxKhuVuc;
    private javax.swing.JComboBox<String> cbxTinhThanhPho;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
