/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GiaodienUI;

import BUS.HoaDon;
import BUS.NhanVien;
import DTO.HoaDonDTO;
import KetnoiSQL_DAL.config;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thanh Tran
 */
public class QlyHoaDon extends javax.swing.JPanel {

    HoaDon danhSachHD = new HoaDon();
    DefaultTableModel model = new DefaultTableModel();

    public QlyHoaDon() {
        initComponents();
        model = (DefaultTableModel) jTable1.getModel();
        for (int i = 0; i < danhSachHD.laySoLuongHoaDon();i++) {
            model.addRow(new Object[]{danhSachHD.traHD(i).getMahd(), danhSachHD.traHD(i).getMakhachdatve(), danhSachHD.traHD(i).getManv(), danhSachHD.traHD(i).getNgayxuathoadon(), danhSachHD.traHD(i).getTongtien()});
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        btnXoa = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(167, 169, 177));

        jPanel1.setBackground(new java.awt.Color(167, 169, 177));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(169, 0, 6));
        jLabel1.setText("                                                Hệ Thống Quản Lý Hóa Đơn");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(167, 169, 177));

        btnXoa.setBackground(new java.awt.Color(21, 110, 71));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnTimKiem.setBackground(new java.awt.Color(21, 110, 71));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnExport.setBackground(new java.awt.Color(21, 110, 71));
        btnExport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExport.setForeground(new java.awt.Color(255, 255, 255));
        btnExport.setText("Export");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(21, 110, 71));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnTimKiem)
                .addGap(50, 50, 50)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Hóa Đơn", "Mã Nhân Viên", "Tổng tiền", "Ngày xuất"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Long.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        
        String maNVCanTim = JOptionPane.showInputDialog(null, "Nhập điều kiện tìm !"," ");

        // Tạo một danh sách để lưu khách hàng tìm được
        ArrayList<HoaDonDTO> ketQuaTimKiem = new ArrayList<>();

        // Lặp qua danh sách khách hàng hiện tại để tìm kiếm
        // Lặp qua danh sách khách hàng hiện tại để tìm kiếm
        for (int i = 0; i < danhSachHD.laySoLuongHoaDon();i++) {
            if (danhSachHD.traHD(i).getMahd().toLowerCase().contains(maNVCanTim.toLowerCase())) {
                ketQuaTimKiem.add(danhSachHD.traHD(i));
            }
        }

// Kiểm tra kết quả tìm kiếm
        if (ketQuaTimKiem.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Kết Quả Không Tìm Thấy");
        } else {

        // Tạo một model mới để hiển thị kết quả tìm kiếm trên JTable
        model.addColumn("Mã hóa đơn");
        model.addColumn("Mã khách hàng");
        model.addColumn("Mã nhân viên");
        model.addColumn("Ngày xuất");
        model.addColumn("Tổng tiền");

        // Thêm các khách hàng tìm được vào model
        model = (DefaultTableModel) jTable1.getModel();
        for (HoaDonDTO nv : ketQuaTimKiem) {
            model.addRow(new Object[]{nv.getMahd(), nv.getMakhachdatve(), nv.getManv(), nv.getNgayxuathoadon(), nv.getTongtien()});
        }
        

        // Cập nhật lại model cho JTable
        jTable1.setModel(model);

    }//GEN-LAST:event_btnTimKiemActionPerformed
    }
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        
        int selectedRow = jTable1.getSelectedRow();

// nếu không có hàng nào được chọn, thông báo lỗi và kết thúc
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Vui Lòng Chọn Một Hàng Để Xóa");
            return;
        }

// lấy ra model của JTable hiện tại
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

// lấy mã khách hàng của hàng được chọn
        String mahoadon = (String) model.getValueAt(selectedRow, 0);

// tìm khách hàng trong danh sách dựa vào mã
        

// xóa khách hàng khỏi danh sách
        danhSachHD.xoaHoaDon(mahoadon);
        
        model.removeRow(selectedRow);

// cập nhật lại model cho JTable
        jTable1.setModel(model);

// thông báo thành công
        JOptionPane.showMessageDialog(null, "Xóa Hóa Đơn Thành Công");

    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        long millis = System.currentTimeMillis();

            // creating a new object of the class Date  
        java.util.Date date = new java.util.Date(millis);
        danhSachHD.themHoaDon(danhSachHD.maHD(),"00012","0001230",15000,date);
    }//GEN-LAST:event_btnExportActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // lấy chỉ số hàng được chọn trong JTable
        
        int selectedRow = jTable1.getSelectedRow();

// nếu không có hàng nào được chọn, thông báo lỗi và kết thúc
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Vui Lòng Chọn Một Hàng Để Sửa");
            return;
        }

// lấy ra model của JTable hiện tại
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
// lấy mã khách hàng của hàng được chọn
        String mahoadon = (String) model.getValueAt(selectedRow, 0);
        String old = mahoadon;
// tìm khách hàng trong danh sách dựa vào mã
        HoaDonDTO hoadonCanSua = null;
        for (int i = 0; i < danhSachHD.laySoLuongHoaDon();i++) {
            if (danhSachHD.traHD(i).getMahd().equals(mahoadon)) {
                hoadonCanSua = danhSachHD.traHD(i);
                break;
            }
        }

// hiển thị form sửa thông tin khách hàng
        String maKH = JOptionPane.showInputDialog(null, "Nhập mã khách hàng", hoadonCanSua.getMakhachdatve());
        String maNVien = JOptionPane.showInputDialog(null, "Nhập mã nhân viên", hoadonCanSua.getManv());
        String maHDnew = JOptionPane.showInputDialog(null, "Nhập mã hóa đơn", hoadonCanSua.getMahd());
        String tongtien = JOptionPane.showInputDialog(null, "Nhập tổng tiền", hoadonCanSua.getTongtien());
        long tongTien = Long.parseLong(tongtien);
// thêm ComboBox để chọn loại nhân viên
        JComboBox<String> cbxNamXuat = new JComboBox<>();
        cbxNamXuat.addItem("2023");

        cbxNamXuat.setSelectedItem(hoadonCanSua.getNgayxuathoadon());

        JOptionPane.showMessageDialog(null, cbxNamXuat, "Chọn năm xuất hóa đơn", JOptionPane.QUESTION_MESSAGE);
        String namDiString = (String) cbxNamXuat.getSelectedItem();
        int namDi = Integer.parseInt(namDiString);

        JComboBox<String> cbxThangXuat = new JComboBox<>();
        for (int i = 1; i < 13; i++) {
            String Day = Integer.toString(i);
            cbxThangXuat.addItem(Day);
            Day = "";
        }
        cbxThangXuat.setSelectedItem(hoadonCanSua.getNgayxuathoadon());
        JOptionPane.showMessageDialog(null, cbxThangXuat, "Chọn tháng xuất hóa đơn", JOptionPane.QUESTION_MESSAGE);
        String TDiString = (String) cbxThangXuat.getSelectedItem();
        int ThangDi = Integer.parseInt(TDiString);

        JComboBox<String> cbxNgayXuat = new JComboBox<>();
        for (int i = 1; i < 32; i++) {
            String Day = Integer.toString(i);
            cbxNgayXuat.addItem(Day);
            Day = "";
        }
        cbxNgayXuat.setSelectedItem(hoadonCanSua.getNgayxuathoadon());
        JOptionPane.showMessageDialog(null, cbxNgayXuat, "Chọn ngày xuất hóa đơn", JOptionPane.QUESTION_MESSAGE);
        String ngaydi = (String) cbxNgayXuat.getSelectedItem();
        int ngayDi = Integer.parseInt(ngaydi);

        Calendar calendar = Calendar.getInstance();
        calendar.set(namDi, ThangDi - 1, ngayDi);
        Date ngayDiDate = calendar.getTime();

        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String ngayDiString = dateFormat.format(ngayDiDate);

// cập nhật thông tin khách hàng
        hoadonCanSua.setMahd(maHDnew);
        hoadonCanSua.setMakhachdatve(maKH);
        hoadonCanSua.setNgayxuathoadon(ngayDiDate);
        hoadonCanSua.setTongtien(tongTien);
        hoadonCanSua.setManv(maNVien);
// cập nhật lại model cho JTable
        model.setValueAt(maHDnew, selectedRow, 0);
        model.setValueAt(maKH, selectedRow, 1);
        model.setValueAt(maNVien, selectedRow, 2);
        model.setValueAt(ngayDiDate, selectedRow, 3);
        model.setValueAt(tongTien, selectedRow, 4);
        
        danhSachHD.suaHoaDon(old, hoadonCanSua.getMahd(), hoadonCanSua.getManv(), hoadonCanSua.getMakhachdatve(), tongTien, ngayDiDate);
// thông báo thành công
        JOptionPane.showMessageDialog(null, "Sửa Thông Tin Hóa Đơn Thành Công");

    }//GEN-LAST:event_btnSuaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
