/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GiaodienUI;

import BUS.NhanVien;
import BUS.VeTour;
import javax.swing.JOptionPane;
import BUS.VeTour;
import DTO.VeTourDTO;
import KetnoiSQL_DAL.config;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thanh Tran
 */
public class QlyVeTour extends javax.swing.JPanel {

    VeTour danhSachVT = new VeTour();
    DefaultTableModel model = new DefaultTableModel();

    public QlyVeTour() {
        initComponents();
        model = (DefaultTableModel) jTable1.getModel();
        for (int i = 0; i < danhSachVT.laySoLuongVeTour(); i++) {
            model.addRow(new Object[]{danhSachVT.traKH(i).getMavetour(), danhSachVT.traKH(i).getMatour(), danhSachVT.traKH(i).ngaydatve, danhSachVT.traKH(i).hansudung, danhSachVT.traKH(i).getTiengiam()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtTienVeGiam = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cbxNgayDatVe = new javax.swing.JComboBox<>();
        cbxThangDatVe = new javax.swing.JComboBox<>();
        cbxNamDatVe = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cbxNgayHanSD = new javax.swing.JComboBox<>();
        cbxThangHanSD = new javax.swing.JComboBox<>();
        cbxNamHanSD = new javax.swing.JComboBox<>();
        btnThem = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(167, 169, 177));

        jPanel1.setBackground(new java.awt.Color(167, 169, 177));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(169, 0, 6));
        jLabel1.setText("                                            Hệ Thống Quản Lý Vé Tour Du Lịch");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(167, 169, 177));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(169, 0, 6));
        jLabel5.setText("     Tiền Vé Giảm");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(169, 0, 6));
        jLabel6.setText("    Ngày Đặt Vé");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        cbxNgayDatVe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ngày" }));
        cbxNgayDatVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNgayDatVeActionPerformed(evt);
            }
        });

        cbxThangDatVe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tháng", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cbxThangDatVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxThangDatVeActionPerformed(evt);
            }
        });

        cbxNamDatVe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Năm", "2023" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(169, 0, 6));
        jLabel7.setText("    Hạn Sử Dụng");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        cbxNgayHanSD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ngày" }));

        cbxThangHanSD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tháng", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cbxThangHanSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxThangHanSDActionPerformed(evt);
            }
        });

        cbxNamHanSD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Năm", "2023" }));

        btnThem.setBackground(new java.awt.Color(21, 110, 71));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        btnXoa.setBackground(new java.awt.Color(21, 110, 71));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(21, 110, 71));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnTimKiem.setBackground(new java.awt.Color(21, 110, 71));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(21, 110, 71));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTienVeGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(btnTimKiem)
                                .addGap(63, 63, 63)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbxNgayDatVe, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbxThangDatVe, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbxNamDatVe, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGap(106, 106, 106)
                                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbxNgayHanSD, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbxThangHanSD, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbxNamHanSD, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTienVeGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxThangDatVe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxNamDatVe, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbxNgayDatVe, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxThangHanSD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxNamHanSD)
                    .addComponent(cbxNgayHanSD, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThem)
                        .addComponent(btnXoa)
                        .addComponent(btnSua)
                        .addComponent(btnTimKiem)))
                .addGap(16, 16, 16))
        );

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Vé Tour", "Mã Tour", "Ngày Đặt Vé", "Hạn Sử Dụng", "Tiền Vé Giảm"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator4))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbxNgayDatVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNgayDatVeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxNgayDatVeActionPerformed

    private void cbxThangDatVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxThangDatVeActionPerformed
        // TODO add your handling code here:
        String thang = cbxThangDatVe.getSelectedItem().toString();
        int day = 0;

//Những tháng 1,3,5,7,8,10,12 thì có 31 ngày trong năm 2023
        if (thang.equals("1")) {
            cbxNgayDatVe.removeAllItems();
            cbxNgayDatVe.addItem("Ngày");
            for (int i = 1; i < 32; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayDatVe.addItem(Day);
                Day = "";
            }
        } else if (thang.equals("3")) {
            cbxNgayDatVe.removeAllItems();
            cbxNgayDatVe.addItem("Ngày");
            for (int i = 1; i < 32; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayDatVe.addItem(Day);
                Day = "";
            }
        } else if (thang.equals("5")) {
            cbxNgayDatVe.removeAllItems();
            cbxNgayDatVe.addItem("Ngày");
            for (int i = 1; i < 32; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayDatVe.addItem(Day);
                Day = "";
            }
        } else if (thang.equals("7")) {
            cbxNgayDatVe.removeAllItems();
            cbxNgayDatVe.addItem("Ngày");
            for (int i = 1; i < 32; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayDatVe.addItem(Day);
                Day = "";
            }
        } else if (thang.equals("8")) {
            cbxNgayDatVe.removeAllItems();
            cbxNgayDatVe.addItem("Ngày");
            for (int i = 1; i < 32; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayDatVe.addItem(Day);
                Day = "";
            }
        } else if (thang.equals("10")) {
            cbxNgayDatVe.removeAllItems();
            cbxNgayDatVe.addItem("Ngày");
            for (int i = 1; i < 32; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayDatVe.addItem(Day);
                Day = "";
            }
        } else if (thang.equals("12")) {
            cbxNgayDatVe.removeAllItems();
            cbxNgayDatVe.addItem("Ngày");
            for (int i = 1; i < 32; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayDatVe.addItem(Day);
                Day = "";
            }
        }

//Những tháng 4,6,9,11 thì có 30 ngày trong năm 2023
        if (thang.equals("4")) {
            cbxNgayDatVe.removeAllItems();
            cbxNgayDatVe.addItem("Ngày");
            for (int i = 1; i < 31; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayDatVe.addItem(Day);
                Day = "";
            }
        } else if (thang.equals("6")) {
            cbxNgayDatVe.removeAllItems();
            cbxNgayDatVe.addItem("Ngày");
            for (int i = 1; i < 31; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayDatVe.addItem(Day);
                Day = "";
            }
        } else if (thang.equals("9")) {
            cbxNgayDatVe.removeAllItems();
            cbxNgayDatVe.addItem("Ngày");
            for (int i = 1; i < 31; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayDatVe.addItem(Day);
                Day = "";
            }
        } else if (thang.equals("11")) {
            cbxNgayDatVe.removeAllItems();
            cbxNgayDatVe.addItem("Ngày");
            for (int i = 1; i < 31; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayDatVe.addItem(Day);
                Day = "";
            }
        }

//Còn lại là tháng 2 có 28 ngày trong năm 2023
        if (thang.equals("2")) {
            cbxNgayDatVe.removeAllItems();
            cbxNgayDatVe.addItem("Ngày");
            for (int i = 1; i < 29; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayDatVe.addItem(Day);
                Day = "";
            }
        }
    }//GEN-LAST:event_cbxThangDatVeActionPerformed

    private void cbxThangHanSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxThangHanSDActionPerformed
        // TODO add your handling code here:
        String thang = cbxThangHanSD.getSelectedItem().toString();
        int day = 0;

//Những tháng 1,3,5,7,8,10,12 thì có 31 ngày trong năm 2023
        if (thang.equals("1")) {
            cbxNgayHanSD.removeAllItems();
            cbxNgayHanSD.addItem("Ngày");
            for (int i = 1; i < 32; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayHanSD.addItem(Day);
                Day = "";
            }
        } else if (thang.equals("3")) {
            cbxNgayHanSD.removeAllItems();
            cbxNgayHanSD.addItem("Ngày");
            for (int i = 1; i < 32; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayHanSD.addItem(Day);
                Day = "";
            }
        } else if (thang.equals("5")) {
            cbxNgayHanSD.removeAllItems();
            cbxNgayHanSD.addItem("Ngày");
            for (int i = 1; i < 32; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayHanSD.addItem(Day);
                Day = "";
            }
        } else if (thang.equals("7")) {
            cbxNgayHanSD.removeAllItems();
            cbxNgayHanSD.addItem("Ngày");
            for (int i = 1; i < 32; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayHanSD.addItem(Day);
                Day = "";
            }
        } else if (thang.equals("8")) {
            cbxNgayHanSD.removeAllItems();
            cbxNgayHanSD.addItem("Ngày");
            for (int i = 1; i < 32; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayHanSD.addItem(Day);
                Day = "";
            }
        } else if (thang.equals("10")) {
            cbxNgayHanSD.removeAllItems();
            cbxNgayHanSD.addItem("Ngày");
            for (int i = 1; i < 32; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayHanSD.addItem(Day);
                Day = "";
            }
        } else if (thang.equals("12")) {
            cbxNgayHanSD.removeAllItems();
            cbxNgayHanSD.addItem("Ngày");
            for (int i = 1; i < 32; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayHanSD.addItem(Day);
                Day = "";
            }
        }

//Những tháng 4,6,9,11 thì có 30 ngày trong năm 2023
        if (thang.equals("4")) {
            cbxNgayHanSD.removeAllItems();
            cbxNgayHanSD.addItem("Ngày");
            for (int i = 1; i < 31; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayHanSD.addItem(Day);
                Day = "";
            }
        } else if (thang.equals("6")) {
            cbxNgayHanSD.removeAllItems();
            cbxNgayHanSD.addItem("Ngày");
            for (int i = 1; i < 31; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayHanSD.addItem(Day);
                Day = "";
            }
        } else if (thang.equals("9")) {
            cbxNgayHanSD.removeAllItems();
            cbxNgayHanSD.addItem("Ngày");
            for (int i = 1; i < 31; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayHanSD.addItem(Day);
                Day = "";
            }
        } else if (thang.equals("11")) {
            cbxNgayHanSD.removeAllItems();
            cbxNgayHanSD.addItem("Ngày");
            for (int i = 1; i < 31; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayHanSD.addItem(Day);
                Day = "";
            }
        }

//Còn lại là tháng 2 có 28 ngày trong năm 2023
        if (thang.equals("2")) {
            cbxNgayHanSD.removeAllItems();
            cbxNgayHanSD.addItem("Ngày");
            for (int i = 1; i < 29; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayHanSD.addItem(Day);
                Day = "";
            }
        }
    }//GEN-LAST:event_cbxThangHanSDActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed

        try {
            int maxMaVT = danhSachVT.laySoLuongVeTour();
            int maxMaTour = danhSachVT.laySoLuongVeTour();
            String maVT = "VT" + String.format("%04d", maxMaVT + 1);
            String maTour = "Tour" + String.format("%04d", maxMaTour + 1);

            long tienGiam = Long.parseLong(txtTienVeGiam.getText());
            int ngayDV = Integer.parseInt(cbxNgayDatVe.getSelectedItem().toString());
            int thangDV = Integer.parseInt(cbxThangDatVe.getSelectedItem().toString());
            int namDV = Integer.parseInt(cbxNamDatVe.getSelectedItem().toString());
            int ngayHSD = Integer.parseInt(cbxNgayHanSD.getSelectedItem().toString());
            int thangHSD = Integer.parseInt(cbxThangHanSD.getSelectedItem().toString());
            int namHSD = Integer.parseInt(cbxNamHanSD.getSelectedItem().toString());

            Calendar calendar = Calendar.getInstance();
            calendar.set(namDV, thangDV - 1, ngayDV);
            Date ngayDVDate = calendar.getTime();
            calendar.set(namHSD, thangHSD - 1, ngayHSD);
            Date hanSDDate = calendar.getTime();

            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            String ngayDVString = dateFormat.format(ngayDVDate);
            String hanSDString = dateFormat.format(hanSDDate);
            danhSachVT.themVeTour(maVT, maTour, tienGiam, ngayDVDate, hanSDDate);
            model.addRow(new Object[]{danhSachVT.traKH(maVT).getMavetour(), danhSachVT.traKH(maVT).getMatour(), ngayDVString, hanSDString, danhSachVT.traKH(maVT).getTiengiam()});
            jTable1.setModel(model);
            JOptionPane.showMessageDialog(null, "Thêm Vé Tour Thành Công");

            txtTienVeGiam.setText("");
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Vui Lòng Nhập Đầy Đủ Thông Tin Và Kiểm Tra Lại");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Vui Lòng Chọn 1 Hàng Để Xóa");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        String maVT = (String) model.getValueAt(selectedRow, 0);

        boolean a = danhSachVT.xoaVeTour(maVT);

        if (a == false) {
            JOptionPane.showMessageDialog(null, "Vé Tour Không Tồn Tại");
            return;
        }

        model.removeRow(selectedRow);

        jTable1.setModel(model);

        JOptionPane.showMessageDialog(null, "Xóa Vé Tour Thành Công");
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed

        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Vui Lòng Chọn 1 Hàng Để Sửa");
        }

        model = (DefaultTableModel) jTable1.getModel();

        String maVT = (String) model.getValueAt(selectedRow, 0);

        danhSachVT.traKH(maVT);
        String MaVT = JOptionPane.showInputDialog(null, "Nhập mã vé tour", danhSachVT.traKH(maVT).getMavetour());
        String MaTour = JOptionPane.showInputDialog(null, "Nhập mã tour", danhSachVT.traKH(maVT).getMatour());

        String TienGiam = JOptionPane.showInputDialog(null, "Nhập tiền vé giảm", danhSachVT.traKH(maVT).getTiengiam());
        Long tienGiamLong = Long.parseLong(TienGiam);
        JComboBox<String> NgayDV = new JComboBox<>();
        for (int i = 1; i < 32; i++) {
            NgayDV.addItem(Integer.toString(i));
        }
        NgayDV.setSelectedItem(danhSachVT.traKH(maVT).getNgaydatve());
        JOptionPane.showMessageDialog(null, NgayDV, "Chọn ngày đặt vé", JOptionPane.QUESTION_MESSAGE);
        int ngayDV = Integer.parseInt(NgayDV.getSelectedItem().toString());

        JComboBox<String> ThangDV = new JComboBox<>();
        for (int i = 1; i < 13; i++) {
            ThangDV.addItem(Integer.toString(i));
        }
        ThangDV.setSelectedItem(danhSachVT.traKH(maVT).getNgaydatve());
        JOptionPane.showMessageDialog(null, ThangDV, "Chọn tháng đặt vé", JOptionPane.QUESTION_MESSAGE);
        int thangDV = Integer.parseInt(ThangDV.getSelectedItem().toString());

        JComboBox<String> NamDV = new JComboBox<>();
        NamDV.addItem("2023");
        NamDV.setSelectedItem(danhSachVT.traKH(maVT).getNgaydatve());
        JOptionPane.showMessageDialog(null, NamDV, "Chọn năm đặt vé", JOptionPane.QUESTION_MESSAGE);
        int namDV = Integer.parseInt(NamDV.getSelectedItem().toString());

        JComboBox<String> NgayHSD = new JComboBox<>();
        for (int i = 1; i < 32; i++) {
            NgayHSD.addItem(Integer.toString(i));
        }
        NgayHSD.setSelectedItem(danhSachVT.traKH(maVT).getHansudung());
        JOptionPane.showMessageDialog(null, NgayHSD, "Chọn ngày hạn sử dụng", JOptionPane.QUESTION_MESSAGE);
        int ngayHSD = Integer.parseInt(NgayHSD.getSelectedItem().toString());

        JComboBox<String> ThangHSD = new JComboBox<>();
        for (int i = 1; i < 13; i++) {
            ThangHSD.addItem(Integer.toString(i));
        }
        ThangHSD.setSelectedItem(danhSachVT.traKH(maVT).getHansudung());
        JOptionPane.showMessageDialog(null, ThangHSD, "Chọn tháng hạn sử dụng", JOptionPane.QUESTION_MESSAGE);
        int thangHSD = Integer.parseInt(ThangHSD.getSelectedItem().toString());

        JComboBox<String> NamHSD = new JComboBox<>();
        NamHSD.addItem("2023");
        NamHSD.setSelectedItem(danhSachVT.traKH(maVT).getHansudung());
        JOptionPane.showMessageDialog(null, NamHSD, "Chọn năm hạn sử dụng", JOptionPane.QUESTION_MESSAGE);
        int namHSD = Integer.parseInt(NamHSD.getSelectedItem().toString());

        Calendar calendar = Calendar.getInstance();
        calendar.set(namDV, thangDV -1 , ngayDV);
        Date ngayDVDate = calendar.getTime();
        calendar.set(namHSD, thangHSD - 1, ngayHSD);
        Date hanSDDate = calendar.getTime();

        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String ngayDVString = dateFormat.format(ngayDVDate);
        String hanSDString = dateFormat.format(hanSDDate);

        danhSachVT.suaVeTour(maVT,MaVT, MaTour, tienGiamLong, ngayDVDate, hanSDDate);

        model.setValueAt(MaVT, selectedRow, 0);
        model.setValueAt(MaTour, selectedRow, 1);

        model.setValueAt(TienGiam, selectedRow, 4);
        model.setValueAt(ngayDVString, selectedRow, 2);
        model.setValueAt(hanSDString, selectedRow, 3);

        jTable1.setModel(model);

        JOptionPane.showMessageDialog(null, "Sửa Thông Tin Vé Tour Thành Công");

    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
       String maNVCanTim = JOptionPane.showInputDialog(null, "Nhập điều kiện tìm !","");

        // Tạo một danh sách để lưu khách hàng tìm được
        danhSachVT.timKhachHangUnlimit(maNVCanTim);
// Kiểm tra kết quả tìm kiếm
        if (danhSachVT.timKhachHangUnlimit(maNVCanTim)==null) {
            JOptionPane.showMessageDialog(null, "Kết Quả Không Tìm Thấy");
        } else {

            // Tạo một model mới để hiển thị kết quả tìm kiếm trên JTable
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Mã vé Tour");
            model.addColumn("Mã Tour");
            model.addColumn("Ngày đặt vé");
            model.addColumn("Hạn sử dụng");
            model.addColumn("Tiền vé giảm");

            // Thêm các khách hàng tìm được vào model
            for (VeTourDTO vt : danhSachVT.timKhachHangUnlimit(maNVCanTim)) {
                model.addRow(new Object[]{vt.getMavetour(), vt.getMatour(), ngayDVString, hanSDString, vt.getTiengiam()});
            }

            // Cập nhật lại model cho JTable
            jTable1.setModel(model);
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        model = (DefaultTableModel) jTable1.getModel();
        for (int i = 0; i < danhSachVT.laySoLuongVeTour(); i++) {
            model.addRow(new Object[]{danhSachVT.traKH(i).getMavetour(), danhSachVT.traKH(i).getMatour(), danhSachVT.traKH(i).ngaydatve, danhSachVT.traKH(i).hansudung, danhSachVT.traKH(i).getTiengiam()});
        }
    }//GEN-LAST:event_btnResetActionPerformed

    private String ngayDVString;
    private String hanSDString;
    private Date ngayDiDate;
    private Date ngayVeDate;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbxNamDatVe;
    private javax.swing.JComboBox<String> cbxNamHanSD;
    private javax.swing.JComboBox<String> cbxNgayDatVe;
    private javax.swing.JComboBox<String> cbxNgayHanSD;
    private javax.swing.JComboBox<String> cbxThangDatVe;
    private javax.swing.JComboBox<String> cbxThangHanSD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtTienVeGiam;
    // End of variables declaration//GEN-END:variables
}
